builds:
  - main: ./cmd/podcli
    binary: podcli
    ldflags: -s -w -X github.com/avatric/podinfo/pkg/version.REVISION={{.Commit}}
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*
