#!/bin/bash

# Register qemu-*-static for all supported processors except the 
# current one, but also remove all registered binfmt_misc before
# docker run --rm --privileged aptman/qus -s -- -p
# docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
mkdir ~/.docker/cli-plugins/
curl -L -o https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64 ~/.docker/cli-plugins/docker-buildx
chmod a+x ~/.docker/cli-plugins/docker-buildx